//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QDBModel", "ViewHierarchy_ObjID_fk", "Object", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MobileDataService.Object), "ViewHierarchy", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MobileDataService.ViewHierarchy), true)]
[assembly: EdmRelationshipAttribute("QDBModel", "Views_RootObjID_fk", "Object", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MobileDataService.Object), "Views", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MobileDataService.View), true)]
[assembly: EdmRelationshipAttribute("QDBModel", "ViewHierarchy_ViewID_fk", "Views", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MobileDataService.View), "ViewHierarchy", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MobileDataService.ViewHierarchy), true)]

#endregion

namespace MobileDataService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QDBEntities object using the connection string found in the 'QDBEntities' section of the application configuration file.
        /// </summary>
        public QDBEntities() : base("name=QDBEntities", "QDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QDBEntities object.
        /// </summary>
        public QDBEntities(string connectionString) : base(connectionString, "QDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QDBEntities object.
        /// </summary>
        public QDBEntities(EntityConnection connection) : base(connection, "QDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Object> Objects
        {
            get
            {
                if ((_Objects == null))
                {
                    _Objects = base.CreateObjectSet<Object>("Objects");
                }
                return _Objects;
            }
        }
        private ObjectSet<Object> _Objects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ViewHierarchy> ViewHierarchies
        {
            get
            {
                if ((_ViewHierarchies == null))
                {
                    _ViewHierarchies = base.CreateObjectSet<ViewHierarchy>("ViewHierarchies");
                }
                return _ViewHierarchies;
            }
        }
        private ObjectSet<ViewHierarchy> _ViewHierarchies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<View> Views
        {
            get
            {
                if ((_Views == null))
                {
                    _Views = base.CreateObjectSet<View>("Views");
                }
                return _Views;
            }
        }
        private ObjectSet<View> _Views;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Objects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToObjects(Object @object)
        {
            base.AddObject("Objects", @object);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ViewHierarchies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToViewHierarchies(ViewHierarchy viewHierarchy)
        {
            base.AddObject("ViewHierarchies", viewHierarchy);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Views EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToViews(View view)
        {
            base.AddObject("Views", view);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="viewId">No Metadata Documentation available.</param>
        /// <param name="parentId">No Metadata Documentation available.</param>
        public ObjectResult<DeviceNode> GetDevices(Nullable<global::System.Int32> viewId, Nullable<global::System.Int32> parentId)
        {
            ObjectParameter viewIdParameter;
            if (viewId.HasValue)
            {
                viewIdParameter = new ObjectParameter("ViewId", viewId);
            }
            else
            {
                viewIdParameter = new ObjectParameter("ViewId", typeof(global::System.Int32));
            }
    
            ObjectParameter parentIdParameter;
            if (parentId.HasValue)
            {
                parentIdParameter = new ObjectParameter("ParentId", parentId);
            }
            else
            {
                parentIdParameter = new ObjectParameter("ParentId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<DeviceNode>("GetDevices", viewIdParameter, parentIdParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QDBModel", Name="Object")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Object : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Object object.
        /// </summary>
        /// <param name="objID">Initial value of the ObjID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="typeID">Initial value of the TypeID property.</param>
        /// <param name="discoveryTime">Initial value of the DiscoveryTime property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="platform">Initial value of the Platform property.</param>
        /// <param name="proxy">Initial value of the Proxy property.</param>
        /// <param name="c1EventCount">Initial value of the C1EventCount property.</param>
        /// <param name="c2EventCount">Initial value of the C2EventCount property.</param>
        /// <param name="c3EventCount">Initial value of the C3EventCount property.</param>
        /// <param name="c4EventCount">Initial value of the C4EventCount property.</param>
        /// <param name="jobCount">Initial value of the JobCount property.</param>
        /// <param name="modificationTime">Initial value of the ModificationTime property.</param>
        /// <param name="isValid">Initial value of the IsValid property.</param>
        /// <param name="isMachine">Initial value of the IsMachine property.</param>
        public static Object CreateObject(global::System.Int32 objID, global::System.String name, global::System.Int32 typeID, global::System.Int32 discoveryTime, global::System.Int32 status, global::System.Int32 platform, global::System.Int32 proxy, global::System.Int32 c1EventCount, global::System.Int32 c2EventCount, global::System.Int32 c3EventCount, global::System.Int32 c4EventCount, global::System.Int32 jobCount, global::System.Int32 modificationTime, global::System.Int32 isValid, global::System.Int32 isMachine)
        {
            Object @object = new Object();
            @object.ObjID = objID;
            @object.Name = name;
            @object.TypeID = typeID;
            @object.DiscoveryTime = discoveryTime;
            @object.Status = status;
            @object.Platform = platform;
            @object.Proxy = proxy;
            @object.C1EventCount = c1EventCount;
            @object.C2EventCount = c2EventCount;
            @object.C3EventCount = c3EventCount;
            @object.C4EventCount = c4EventCount;
            @object.JobCount = jobCount;
            @object.ModificationTime = modificationTime;
            @object.IsValid = isValid;
            @object.IsMachine = isMachine;
            return @object;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ObjID
        {
            get
            {
                return _ObjID;
            }
            set
            {
                if (_ObjID != value)
                {
                    OnObjIDChanging(value);
                    ReportPropertyChanging("ObjID");
                    _ObjID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ObjID");
                    OnObjIDChanged();
                }
            }
        }
        private global::System.Int32 _ObjID;
        partial void OnObjIDChanging(global::System.Int32 value);
        partial void OnObjIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TypeID
        {
            get
            {
                return _TypeID;
            }
            set
            {
                OnTypeIDChanging(value);
                ReportPropertyChanging("TypeID");
                _TypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TypeID");
                OnTypeIDChanged();
            }
        }
        private global::System.Int32 _TypeID;
        partial void OnTypeIDChanging(global::System.Int32 value);
        partial void OnTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DiscoveryTime
        {
            get
            {
                return _DiscoveryTime;
            }
            set
            {
                OnDiscoveryTimeChanging(value);
                ReportPropertyChanging("DiscoveryTime");
                _DiscoveryTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiscoveryTime");
                OnDiscoveryTimeChanged();
            }
        }
        private global::System.Int32 _DiscoveryTime;
        partial void OnDiscoveryTimeChanging(global::System.Int32 value);
        partial void OnDiscoveryTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Platform
        {
            get
            {
                return _Platform;
            }
            set
            {
                OnPlatformChanging(value);
                ReportPropertyChanging("Platform");
                _Platform = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Platform");
                OnPlatformChanged();
            }
        }
        private global::System.Int32 _Platform;
        partial void OnPlatformChanging(global::System.Int32 value);
        partial void OnPlatformChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Proxy
        {
            get
            {
                return _Proxy;
            }
            set
            {
                OnProxyChanging(value);
                ReportPropertyChanging("Proxy");
                _Proxy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Proxy");
                OnProxyChanged();
            }
        }
        private global::System.Int32 _Proxy;
        partial void OnProxyChanging(global::System.Int32 value);
        partial void OnProxyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C1EventCount
        {
            get
            {
                return _C1EventCount;
            }
            set
            {
                OnC1EventCountChanging(value);
                ReportPropertyChanging("C1EventCount");
                _C1EventCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C1EventCount");
                OnC1EventCountChanged();
            }
        }
        private global::System.Int32 _C1EventCount;
        partial void OnC1EventCountChanging(global::System.Int32 value);
        partial void OnC1EventCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C2EventCount
        {
            get
            {
                return _C2EventCount;
            }
            set
            {
                OnC2EventCountChanging(value);
                ReportPropertyChanging("C2EventCount");
                _C2EventCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C2EventCount");
                OnC2EventCountChanged();
            }
        }
        private global::System.Int32 _C2EventCount;
        partial void OnC2EventCountChanging(global::System.Int32 value);
        partial void OnC2EventCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C3EventCount
        {
            get
            {
                return _C3EventCount;
            }
            set
            {
                OnC3EventCountChanging(value);
                ReportPropertyChanging("C3EventCount");
                _C3EventCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C3EventCount");
                OnC3EventCountChanged();
            }
        }
        private global::System.Int32 _C3EventCount;
        partial void OnC3EventCountChanging(global::System.Int32 value);
        partial void OnC3EventCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C4EventCount
        {
            get
            {
                return _C4EventCount;
            }
            set
            {
                OnC4EventCountChanging(value);
                ReportPropertyChanging("C4EventCount");
                _C4EventCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C4EventCount");
                OnC4EventCountChanged();
            }
        }
        private global::System.Int32 _C4EventCount;
        partial void OnC4EventCountChanging(global::System.Int32 value);
        partial void OnC4EventCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 JobCount
        {
            get
            {
                return _JobCount;
            }
            set
            {
                OnJobCountChanging(value);
                ReportPropertyChanging("JobCount");
                _JobCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JobCount");
                OnJobCountChanged();
            }
        }
        private global::System.Int32 _JobCount;
        partial void OnJobCountChanging(global::System.Int32 value);
        partial void OnJobCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RootMachineObjID
        {
            get
            {
                return _RootMachineObjID;
            }
            set
            {
                OnRootMachineObjIDChanging(value);
                ReportPropertyChanging("RootMachineObjID");
                _RootMachineObjID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RootMachineObjID");
                OnRootMachineObjIDChanged();
            }
        }
        private Nullable<global::System.Int32> _RootMachineObjID;
        partial void OnRootMachineObjIDChanging(Nullable<global::System.Int32> value);
        partial void OnRootMachineObjIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String String1
        {
            get
            {
                return _String1;
            }
            set
            {
                OnString1Changing(value);
                ReportPropertyChanging("String1");
                _String1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("String1");
                OnString1Changed();
            }
        }
        private global::System.String _String1;
        partial void OnString1Changing(global::System.String value);
        partial void OnString1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String String2
        {
            get
            {
                return _String2;
            }
            set
            {
                OnString2Changing(value);
                ReportPropertyChanging("String2");
                _String2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("String2");
                OnString2Changed();
            }
        }
        private global::System.String _String2;
        partial void OnString2Changing(global::System.String value);
        partial void OnString2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String String3
        {
            get
            {
                return _String3;
            }
            set
            {
                OnString3Changing(value);
                ReportPropertyChanging("String3");
                _String3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("String3");
                OnString3Changed();
            }
        }
        private global::System.String _String3;
        partial void OnString3Changing(global::System.String value);
        partial void OnString3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String String4
        {
            get
            {
                return _String4;
            }
            set
            {
                OnString4Changing(value);
                ReportPropertyChanging("String4");
                _String4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("String4");
                OnString4Changed();
            }
        }
        private global::System.String _String4;
        partial void OnString4Changing(global::System.String value);
        partial void OnString4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String String5
        {
            get
            {
                return _String5;
            }
            set
            {
                OnString5Changing(value);
                ReportPropertyChanging("String5");
                _String5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("String5");
                OnString5Changed();
            }
        }
        private global::System.String _String5;
        partial void OnString5Changing(global::System.String value);
        partial void OnString5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String String6
        {
            get
            {
                return _String6;
            }
            set
            {
                OnString6Changing(value);
                ReportPropertyChanging("String6");
                _String6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("String6");
                OnString6Changed();
            }
        }
        private global::System.String _String6;
        partial void OnString6Changing(global::System.String value);
        partial void OnString6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String String7
        {
            get
            {
                return _String7;
            }
            set
            {
                OnString7Changing(value);
                ReportPropertyChanging("String7");
                _String7 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("String7");
                OnString7Changed();
            }
        }
        private global::System.String _String7;
        partial void OnString7Changing(global::System.String value);
        partial void OnString7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String String8
        {
            get
            {
                return _String8;
            }
            set
            {
                OnString8Changing(value);
                ReportPropertyChanging("String8");
                _String8 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("String8");
                OnString8Changed();
            }
        }
        private global::System.String _String8;
        partial void OnString8Changing(global::System.String value);
        partial void OnString8Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModificationTime
        {
            get
            {
                return _ModificationTime;
            }
            set
            {
                OnModificationTimeChanging(value);
                ReportPropertyChanging("ModificationTime");
                _ModificationTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModificationTime");
                OnModificationTimeChanged();
            }
        }
        private global::System.Int32 _ModificationTime;
        partial void OnModificationTimeChanging(global::System.Int32 value);
        partial void OnModificationTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RootSrvObjID
        {
            get
            {
                return _RootSrvObjID;
            }
            set
            {
                OnRootSrvObjIDChanging(value);
                ReportPropertyChanging("RootSrvObjID");
                _RootSrvObjID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RootSrvObjID");
                OnRootSrvObjIDChanged();
            }
        }
        private Nullable<global::System.Int32> _RootSrvObjID;
        partial void OnRootSrvObjIDChanging(Nullable<global::System.Int32> value);
        partial void OnRootSrvObjIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> QDW_Flag
        {
            get
            {
                return _QDW_Flag;
            }
            set
            {
                OnQDW_FlagChanging(value);
                ReportPropertyChanging("QDW_Flag");
                _QDW_Flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QDW_Flag");
                OnQDW_FlagChanged();
            }
        }
        private Nullable<global::System.Byte> _QDW_Flag;
        partial void OnQDW_FlagChanging(Nullable<global::System.Byte> value);
        partial void OnQDW_FlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IsValid
        {
            get
            {
                return _IsValid;
            }
            set
            {
                OnIsValidChanging(value);
                ReportPropertyChanging("IsValid");
                _IsValid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsValid");
                OnIsValidChanged();
            }
        }
        private global::System.Int32 _IsValid;
        partial void OnIsValidChanging(global::System.Int32 value);
        partial void OnIsValidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IsMachine
        {
            get
            {
                return _IsMachine;
            }
            set
            {
                OnIsMachineChanging(value);
                ReportPropertyChanging("IsMachine");
                _IsMachine = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMachine");
                OnIsMachineChanged();
            }
        }
        private global::System.Int32 _IsMachine;
        partial void OnIsMachineChanging(global::System.Int32 value);
        partial void OnIsMachineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LinkID
        {
            get
            {
                return _LinkID;
            }
            set
            {
                OnLinkIDChanging(value);
                ReportPropertyChanging("LinkID");
                _LinkID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LinkID");
                OnLinkIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LinkID;
        partial void OnLinkIDChanging(Nullable<global::System.Int32> value);
        partial void OnLinkIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProxyMachineObjID
        {
            get
            {
                return _ProxyMachineObjID;
            }
            set
            {
                OnProxyMachineObjIDChanging(value);
                ReportPropertyChanging("ProxyMachineObjID");
                _ProxyMachineObjID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProxyMachineObjID");
                OnProxyMachineObjIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ProxyMachineObjID;
        partial void OnProxyMachineObjIDChanging(Nullable<global::System.Int32> value);
        partial void OnProxyMachineObjIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QDBModel", "ViewHierarchy_ObjID_fk", "ViewHierarchy")]
        public EntityCollection<ViewHierarchy> ViewHierarchies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ViewHierarchy>("QDBModel.ViewHierarchy_ObjID_fk", "ViewHierarchy");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ViewHierarchy>("QDBModel.ViewHierarchy_ObjID_fk", "ViewHierarchy", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QDBModel", "Views_RootObjID_fk", "Views")]
        public EntityCollection<View> Views
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<View>("QDBModel.Views_RootObjID_fk", "Views");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<View>("QDBModel.Views_RootObjID_fk", "Views", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QDBModel", Name="View")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class View : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new View object.
        /// </summary>
        /// <param name="viewID">Initial value of the ViewID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="createUserID">Initial value of the CreateUserID property.</param>
        /// <param name="createTime">Initial value of the CreateTime property.</param>
        /// <param name="rootObjID">Initial value of the RootObjID property.</param>
        /// <param name="modificationTime">Initial value of the ModificationTime property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static View CreateView(global::System.Int32 viewID, global::System.String name, global::System.Byte[] createUserID, global::System.Int32 createTime, global::System.Int32 rootObjID, global::System.Int32 modificationTime, global::System.Int32 status)
        {
            View view = new View();
            view.ViewID = viewID;
            view.Name = name;
            view.CreateUserID = createUserID;
            view.CreateTime = createTime;
            view.RootObjID = rootObjID;
            view.ModificationTime = modificationTime;
            view.Status = status;
            return view;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ViewID
        {
            get
            {
                return _ViewID;
            }
            set
            {
                if (_ViewID != value)
                {
                    OnViewIDChanging(value);
                    ReportPropertyChanging("ViewID");
                    _ViewID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ViewID");
                    OnViewIDChanged();
                }
            }
        }
        private global::System.Int32 _ViewID;
        partial void OnViewIDChanging(global::System.Int32 value);
        partial void OnViewIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] CreateUserID
        {
            get
            {
                return StructuralObject.GetValidValue(_CreateUserID);
            }
            set
            {
                OnCreateUserIDChanging(value);
                ReportPropertyChanging("CreateUserID");
                _CreateUserID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreateUserID");
                OnCreateUserIDChanged();
            }
        }
        private global::System.Byte[] _CreateUserID;
        partial void OnCreateUserIDChanging(global::System.Byte[] value);
        partial void OnCreateUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.Int32 _CreateTime;
        partial void OnCreateTimeChanging(global::System.Int32 value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MapID
        {
            get
            {
                return _MapID;
            }
            set
            {
                OnMapIDChanging(value);
                ReportPropertyChanging("MapID");
                _MapID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MapID");
                OnMapIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MapID;
        partial void OnMapIDChanging(Nullable<global::System.Int32> value);
        partial void OnMapIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RootObjID
        {
            get
            {
                return _RootObjID;
            }
            set
            {
                OnRootObjIDChanging(value);
                ReportPropertyChanging("RootObjID");
                _RootObjID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RootObjID");
                OnRootObjIDChanged();
            }
        }
        private global::System.Int32 _RootObjID;
        partial void OnRootObjIDChanging(global::System.Int32 value);
        partial void OnRootObjIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModificationTime
        {
            get
            {
                return _ModificationTime;
            }
            set
            {
                OnModificationTimeChanging(value);
                ReportPropertyChanging("ModificationTime");
                _ModificationTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModificationTime");
                OnModificationTimeChanged();
            }
        }
        private global::System.Int32 _ModificationTime;
        partial void OnModificationTimeChanging(global::System.Int32 value);
        partial void OnModificationTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ViewType
        {
            get
            {
                return _ViewType;
            }
            set
            {
                OnViewTypeChanging(value);
                ReportPropertyChanging("ViewType");
                _ViewType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ViewType");
                OnViewTypeChanged();
            }
        }
        private global::System.String _ViewType;
        partial void OnViewTypeChanging(global::System.String value);
        partial void OnViewTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QDBModel", "Views_RootObjID_fk", "Object")]
        public Object Object
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Object>("QDBModel.Views_RootObjID_fk", "Object").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Object>("QDBModel.Views_RootObjID_fk", "Object").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Object> ObjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Object>("QDBModel.Views_RootObjID_fk", "Object");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Object>("QDBModel.Views_RootObjID_fk", "Object", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QDBModel", "ViewHierarchy_ViewID_fk", "ViewHierarchy")]
        public EntityCollection<ViewHierarchy> ViewHierarchies
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ViewHierarchy>("QDBModel.ViewHierarchy_ViewID_fk", "ViewHierarchy");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ViewHierarchy>("QDBModel.ViewHierarchy_ViewID_fk", "ViewHierarchy", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QDBModel", Name="ViewHierarchy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ViewHierarchy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ViewHierarchy object.
        /// </summary>
        /// <param name="viewID">Initial value of the ViewID property.</param>
        /// <param name="objID">Initial value of the ObjID property.</param>
        /// <param name="iconID">Initial value of the IconID property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static ViewHierarchy CreateViewHierarchy(global::System.Int32 viewID, global::System.Int32 objID, global::System.Int32 iconID, global::System.Int32 status)
        {
            ViewHierarchy viewHierarchy = new ViewHierarchy();
            viewHierarchy.ViewID = viewID;
            viewHierarchy.ObjID = objID;
            viewHierarchy.IconID = iconID;
            viewHierarchy.Status = status;
            return viewHierarchy;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ViewID
        {
            get
            {
                return _ViewID;
            }
            set
            {
                if (_ViewID != value)
                {
                    OnViewIDChanging(value);
                    ReportPropertyChanging("ViewID");
                    _ViewID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ViewID");
                    OnViewIDChanged();
                }
            }
        }
        private global::System.Int32 _ViewID;
        partial void OnViewIDChanging(global::System.Int32 value);
        partial void OnViewIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ObjID
        {
            get
            {
                return _ObjID;
            }
            set
            {
                if (_ObjID != value)
                {
                    OnObjIDChanging(value);
                    ReportPropertyChanging("ObjID");
                    _ObjID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ObjID");
                    OnObjIDChanged();
                }
            }
        }
        private global::System.Int32 _ObjID;
        partial void OnObjIDChanging(global::System.Int32 value);
        partial void OnObjIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentObjID
        {
            get
            {
                return _ParentObjID;
            }
            set
            {
                OnParentObjIDChanging(value);
                ReportPropertyChanging("ParentObjID");
                _ParentObjID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentObjID");
                OnParentObjIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentObjID;
        partial void OnParentObjIDChanging(Nullable<global::System.Int32> value);
        partial void OnParentObjIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IconID
        {
            get
            {
                return _IconID;
            }
            set
            {
                OnIconIDChanging(value);
                ReportPropertyChanging("IconID");
                _IconID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IconID");
                OnIconIDChanged();
            }
        }
        private global::System.Int32 _IconID;
        partial void OnIconIDChanging(global::System.Int32 value);
        partial void OnIconIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModificationTime
        {
            get
            {
                return _ModificationTime;
            }
            set
            {
                OnModificationTimeChanging(value);
                ReportPropertyChanging("ModificationTime");
                _ModificationTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModificationTime");
                OnModificationTimeChanged();
            }
        }
        private Nullable<global::System.Int32> _ModificationTime;
        partial void OnModificationTimeChanging(Nullable<global::System.Int32> value);
        partial void OnModificationTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> QDW_Flag
        {
            get
            {
                return _QDW_Flag;
            }
            set
            {
                OnQDW_FlagChanging(value);
                ReportPropertyChanging("QDW_Flag");
                _QDW_Flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QDW_Flag");
                OnQDW_FlagChanged();
            }
        }
        private Nullable<global::System.Byte> _QDW_Flag;
        partial void OnQDW_FlagChanging(Nullable<global::System.Byte> value);
        partial void OnQDW_FlagChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QDBModel", "ViewHierarchy_ObjID_fk", "Object")]
        public Object Object
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Object>("QDBModel.ViewHierarchy_ObjID_fk", "Object").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Object>("QDBModel.ViewHierarchy_ObjID_fk", "Object").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Object> ObjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Object>("QDBModel.ViewHierarchy_ObjID_fk", "Object");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Object>("QDBModel.ViewHierarchy_ObjID_fk", "Object", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QDBModel", "ViewHierarchy_ViewID_fk", "Views")]
        public View View
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<View>("QDBModel.ViewHierarchy_ViewID_fk", "Views").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<View>("QDBModel.ViewHierarchy_ViewID_fk", "Views").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<View> ViewReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<View>("QDBModel.ViewHierarchy_ViewID_fk", "Views");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<View>("QDBModel.ViewHierarchy_ViewID_fk", "Views", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="QDBModel", Name="DeviceNode")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class DeviceNode : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private Nullable<global::System.Int32> _id;
        partial void OnidChanging(Nullable<global::System.Int32> value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> parentid
        {
            get
            {
                return _parentid;
            }
            set
            {
                OnparentidChanging(value);
                ReportPropertyChanging("parentid");
                _parentid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parentid");
                OnparentidChanged();
            }
        }
        private Nullable<global::System.Int32> _parentid;
        partial void OnparentidChanging(Nullable<global::System.Int32> value);
        partial void OnparentidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    }

    #endregion
    
}
